version: "3.9"

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    networks:
      - database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/posgressql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database

networks:
  database:

volumes:
  db: