import Head from "next/head";
import { api } from "../utils/api";

export default function BuildsPage() {
  const builds = api.builds.getBuilds.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-b text-white from-[#2e026d] to-[#15162c]">
        <h1>Builds</h1>

        <table>
          <thead>
          <tr>
            <th>Id</th>
            <th>Match Up</th>
            <th>Build</th>
          </tr>
          </thead>

          <tbody>
          {/* eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access */}
          {builds.data?.map(({ build, id, matchUp }) => (
            <tr key={id as string}>
              <td>{id}</td>
              <td>{matchUp}</td>
              <td>{build}</td>
            </tr>
          ))}
          </tbody>
        </table>
      </main>
    </>
  );
}