import { type NextPage } from "next";
import Head from "next/head";
import type { FormEvent } from "react";
import { useState } from "react";

import { api } from "../utils/api";
import { useRouter } from "next/router";

const CreateBuildPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();

  const [buildOrder, setBuildOrder] = useState("");
  const [matchUp, setMatchUp] = useState("zvp");

  const router = useRouter();

  async function handleSubmitBuildOrder(e: FormEvent) {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build: buildOrder,
    });

    await router.push("/builds");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-b text-white from-[#2e026d] to-[#15162c]">
        <h1>Submit a build order</h1>

        <form
          className={"flex flex-col gap-4"}
          /* eslint-disable-next-line @typescript-eslint/no-misused-promises */
          onSubmit={handleSubmitBuildOrder}>
          <label htmlFor="match-up-select">
            Match Up
          </label>
          <select
            className={"text-black"}
            id="match-up-select"
            onChange={(e) => setMatchUp(e.target.value)}
            value={matchUp}
            required>
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>

            <option value="pvt">PvT</option>
            <option value="pvp">PvP</option>
            <option value="pvz">PvZ</option>

            <option value="tvt">TvT</option>
            <option value="tvp">TvP</option>
            <option value="tvz">TvZ</option>
          </select>

          <textarea
            className={"p-5 text-black"}
            value={buildOrder}
            onChange={(e) => setBuildOrder(e.target.value)} />

          <button className={"p-2 bg-white text-black"}>Submit</button>
        </form>
      </main>
    </>
  );
};

export default CreateBuildPage;

