import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-b text-white from-[#2e026d] to-[#15162c]">
        <h1>Welcome to sc2 build order</h1>
        <Link href={"/create-build"}>Create build page</Link>
      </main>
    </>
  );
};

export default Home;
